### ISSUE TITLE
BSC Bridge токены не зачислены на кошелек TON

### ISSUE THREAD

**Issue by maks-okhmatenko** [newton-blockchain/newton-blockchain.github.io#14]
Вчера 12.11.2021 купил через pancake swap на сумму 1000 busd, отправил через мост на свой ton кошелёк и первая транзакция дошла. Я ее сразу благополучно отправил на биржу.

Решил так же докупить но уже на 2000 busd, все абсолютно по той же схеме. Но второй раз при отправке через мост, токены просто не были зачислены на ton кошелек. 

Ссылка на транзакцию на bsc
https://bscscan.com/tx/0x3ac9ed09d1d80875972577a3ab392abb41a3c4ac99cccba8ad06457bc07d423e

Ссылка на кошелек TON
https://ton.sh/address/EQDSFiCsWv18MSAgKtG5t67Nmha0z0Ea7GB4uS7OtUiZLk8t

**Comment by tolya-yanot** [comment]
https://t.me/toncoin_help
